### PR TITLE
Changes related to release of dplyr 1.0.1

### PR DESCRIPTION
**Pull request by romainfrancois**
These minor changes makes the package pass tests against `dplyr` 1.0.1. It is not clear why the tests failed before and it looks like a `vctrs::vec_rbind()` issue when working with objects of class `"table"`. This works around the problem.

### CODE REVIEW

**Comment by romainfrancois** [comment]
For reference @lionel- @DavisVaughan without these changes, I'm getting: 

```
test-Initialization.R:88: error: Documents with length 0: base
Internal error in `vec_proxy_assign_opts()`: `proxy` of type `integer` incompatible with `value` proxy of type `double`.
Backtrace:
  1. testthat::expect_warning(...) tests/testthat/test-Initialization.R:88:2
  6. keyATM::keyATM(...)
  7. keyATM::keyATM_output(fitted, keep) R/keyATM.R:111:2
  8. keyATM::keyATM_output_theta(model, info) R/posterior.R:33:2
 11. vctrs::vec_rbind(!!!dots, .names_to = .id) /Users/romainfrancois/git/tidyverse/dplyr/R/bind.r:131:2
```

I'll copy this reprex in a new `vctrs` issue: 

``` r
library(vctrs)

vec_rbind(
  table(c(1, 2)) / 2, 
  table(c(1, 2)) / 2
)
#> Error: Internal error in `vec_proxy_assign_opts()`: `proxy` of type `integer` incompatible with `value` proxy of type `double`.
#> Backtrace:
#>     █
#>  1. └─vctrs::vec_rbind(table(c(1, 2))/2, table(c(1, 2))/2)
#>  2.   └─(function () ...
```

<sup>Created on 2020-07-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by Shusei-E** [comment]
@romainfrancois  Thank you for the pull request!

I found the point you raised is in `vctrs`'s issue (https://github.com/r-lib/vctrs/issues/1190). I will check if there is any updates on this point before the release of `dplyr 1.0.1` on CRAN.

I also need to check the line you skipped in `test-Initialization.R` (https://github.com/keyATM/keyATM/pull/145/commits/5848d59d748373dbdce4330b259cdeb8f08e810f#diff-4db583c52b6f91d9789f2884f90d3401R34). With my understanding, the line is not related to the `vctrs` issue.

Thanks again for proposing a way to get around the issue!!

**Comment by romainfrancois** [comment]
We've received these problems from cran when trying to release dplyr 1.0.1 : 

```
Package: keyATM
Check: tests
New result: ERROR
   Running ‘testthat.R’ [15s/15s]
 Running the tests in ‘tests/testthat.R’ failed.
 Complete output:
library(testthat)
library(keyATM)
   keyATM 0.3.0 successfully loaded.
    Papers, examples, resources, and other materials are at
    https://keyatm.github.io/keyATM/

test_check("keyATM")
   0%   10   20   30   40   50   60   70   80   90   100%
   [----|----|----|----|----|----|----|----|----|----|
   **************************************************|
   ── 1. Error: (unknown) (@test-keyATMBase.R#16)
────────────────────────────────
   Internal error in `vec_proxy_assign_opts()`: `proxy` of type
`integer` incompatible with `value` proxy of type `double`.
   Backtrace:
    1. keyATM::keyATM(...)
    2. keyATM:::keyATM_output(fitted, keep)
    3. keyATM:::keyATM_output_theta(model, info)
    6. vctrs::vec_rbind(!!!dots, .names_to = .id)

   0%   10   20   30   40   50   60   70   80   90   100%
   [----|----|----|----|----|----|----|----|----|----|
   **************************************************|
   ── 2. Error: (unknown) (@test-keyATMCov.R#17)
─────────────────────────────────
   Internal error in `vec_proxy_assign_opts()`: `proxy` of type
`integer` incompatible with `value` proxy of type `double`.
   Backtrace:
    1. keyATM::keyATM(...)
    2. keyATM:::keyATM_output(fitted, keep)
    3. keyATM:::keyATM_output_theta(model, info)
    6. vctrs::vec_rbind(!!!dots, .names_to = .id)

   0%   10   20   30   40   50   60   70   80   90   100%
   [----|----|----|----|----|----|----|----|----|----|
   **************************************************|
   ── 3. Error: (unknown) (@test-keyATMDynamic.R#17)
─────────────────────────────
   'x' must be numeric
   Backtrace:
    1. keyATM::keyATM(...)
    2. keyATM:::keyATM_output(fitted, keep)
    3. keyATM:::keyATM_output_theta(model, info)
    5. Matrix::rowSums(tt)
    6. base::rowSums(x, na.rm = na.rm, dims = dims, ...)

   0%   10   20   30   40   50   60   70   80   90   100%
   [----|----|----|----|----|----|----|----|----|----|
   **************************************************|
   ── 4. Error: (unknown) (@test-keyATMHeterogeneity.R#51)
───────────────────────
   Internal error in `vec_proxy_assign_opts()`: `proxy` of type
`integer` incompatible with `value` proxy of type `double`.
   Backtrace:
    1. keyATM::keyATM(...)
    2. keyATM:::keyATM_output(fitted, keep)
    3. keyATM:::keyATM_output_theta(model, info)
    6. vctrs::vec_rbind(!!!dots, .names_to = .id)

   0%   10   20   30   40   50   60   70   80   90   100%
   [----|----|----|----|----|----|----|----|----|----|
   **************************************************|
   Perplexity [1]: 10446.7 / Convergence [1]: 1
   Perplexity [2]: 9778.84 / Convergence [2]: 0.0639325
   Perplexity [3]: 9158.22 / Convergence [3]: 0.0634658
   Perplexity [4]: 8693.21 / Convergence [4]: 0.0507752
   Perplexity [5]: 8350.53 / Convergence [5]: 0.0394192
   ── 5. Error: (unknown) (@test-keyATMvb.R#14)
──────────────────────────────────
   Internal error in `vec_proxy_assign_opts()`: `proxy` of type
`integer` incompatible with `value` proxy of type `double`.
   Backtrace:
    1. keyATM::keyATMvb(...)
    2. keyATM:::keyATM_output(fitted, keep)
    3. keyATM:::keyATM_output_theta(model, info)
    6. vctrs::vec_rbind(!!!dots, .names_to = .id)

   0%   10   20   30   40   50   60   70   80   90   100%
   [----|----|----|----|----|----|----|----|----|----|
   **************************************************|
   ── 6. Error: (unknown) (@test-plot.R#16)
──────────────────────────────────────
   Internal error in `vec_proxy_assign_opts()`: `proxy` of type
`integer` incompatible with `value` proxy of type `double`.
   Backtrace:
    1. keyATM::keyATM(...)
    2. keyATM:::keyATM_output(fitted, keep)
    3. keyATM:::keyATM_output_theta(model, info)
    6. vctrs::vec_rbind(!!!dots, .names_to = .id)

   ══ testthat results
═══════════════════════════════════════════════════════════
   [ OK: 17 | SKIPPED: 9 | WARNINGS: 0 | FAILED: 6 ]
   1. Error: (unknown) (@test-keyATMBase.R#16)
   2. Error: (unknown) (@test-keyATMCov.R#17)
   3. Error: (unknown) (@test-keyATMDynamic.R#17)
   4. Error: (unknown) (@test-keyATMHeterogeneity.R#51)
   5. Error: (unknown) (@test-keyATMvb.R#14)
   6. Error: (unknown) (@test-plot.R#16)

   Error: testthat unit tests failed
   Execution halted

Package: naniar
Check: tests
New result: ERROR
   Running ‘spelling.R’ [0s/0s]
   Running ‘testthat.R’ [11s/11s]
 Running the tests in ‘tests/testthat.R’ failed.
```

I believe the workaround offered here would do the trick. Would you consider releasing ?

**Comment by Shusei-E** [comment]
Hi @romainfrancois, thanks! Got it. I will use the patch you offered, later today or tomorrow.

 Do you mind if I add you to the list of contributors?
(I don't know the exact rule, but it seems people add everyone who contributed to the code https://github.com/keyATM/keyATM/blob/package_dev/DESCRIPTION)

**Comment by romainfrancois** [comment]
I don't mind one way or another. If you do you can use 

```
person(given = "Romain",
             family = "François",
             role = "ctb",
             comment = c(ORCID = "0000-0002-2444-4226"))
```

**Pull request merged**
