### PR TITLE
Update the package

### PR DESCRIPTION
**Pull request by Shusei-E**
Is there any missing TRUE/FALSE? (we cannot use T/F)

### CODE REVIEW

**Comment by tomoya-sasaki** [comment]
@Shusei-E I have edited some. Could you check please?

**Comment by Shusei-E** [comment]
@tomoya-sasaki You mean I have anything to review?

**Comment by tomoya-sasaki** [comment]
> @tomoya-sasaki You mean I have anything to review?

Yes, could you check the part I have modified?

**Comment by Shusei-E** [comment]
@tomoya-sasaki Looks great! I requested a review again.

**Comment by Shusei-E** [comment]
@Mergifyio refresh

**Comment by Shusei-E** [comment]
@Mergifyio refresh

**Comment by Shusei-E** [comment]
@Mergifyio update

**Pull request closed without merging**
